packages:
  - apps/storybook/
  # - packages/schemas/*
  - packages/utils/
  - packages/utils/*
  - packages/structs/*
  - packages/ui/*
  # - packages/ai/*
  - packages/types
  # - packages/procgen/*
  - ui/*
  - tooling/*
catalog:
  eslint: ^9.7.0
  hash-wasm: ^4.11.0
  jest: ^29.7.0
  ts-jest: ^29.1.5
  "@types/jest": ^29.5.12
  openai: ^4.55.7
  pino: ^9.3.2
  pino-pretty: ^11.2.2
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  tsup: ^8.2.4
  typescript: ^5.5.3
  zod: ^3.23.8
catalogs:
  pino:
    pino: ^9.3.2
    pino-pretty: ^11.2.2
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  tailwind:
    tailwindcss: ^3.4.10
